feat/migrate-sample
sendbird/sendbird-uikit-react-native pull request #187
Opened 2024-07-09 05:25 UTC by OnestarLee

## External Contributions

This project is not yet set up to accept pull requests from external contributors.

If you have a pull request that you believe should be accepted, please contact
the Developer Relations team <developer-advocates@sendbird.com> with details
and we'll evaluate if we can setup a [CLA](https://en.wikipedia.org/wiki/Contributor_License_Agreement) to allow for the contribution.

## For Internal Contributors

[CLNP-2240](https://sendbird.atlassian.net/browse/CLNP-2240)

## Description Of Changes

## Types Of Changes

What types of changes does your code introduce to this project?
Put an `x` in the boxes that apply_

- [ ] Bugfix
- [ ] New feature
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance (ex) Prettier)
- [x] Build configuration
- [ ] Improvement (refactor code)
- [ ] Test

2024-07-09 05:51 UTC, bang9 commented on packages/uikit-react-native/src/fragments/createGroupChannelFragment.tsx
> +      voiceMessageStatusManager.clear();
```suggestion
```

2024-07-09 05:54 UTC, bang9 commented on packages/uikit-react-native/package.json
> -    "@sendbird/react-native-scrollview-enhancer": "^0.2.1",
```diff
+     "@sendbird/react-native-scrollview-enhancer": "^0.2.1",
```

2024-07-09 05:55 UTC, bang9 commented on packages/uikit-react-native/package.json
> -    "@sendbird/react-native-scrollview-enhancer": "^0.2.1",
샘플에서만 제거하면 될거같은데, 한번 체크해주실 수 있을까용?

2024-07-09 06:59 UTC, OnestarLee commented on packages/uikit-react-native/package.json
> -    "@sendbird/react-native-scrollview-enhancer": "^0.2.1",
```
function getFlatList(): FlatListBidirectional {
  if (shouldUseScrollViewEnhancer()) {
    try {
      return require('@sendbird/react-native-scrollview-enhancer').FlatList;
    } catch {
      return require('react-native').FlatList;
    }
  } else {
    return require('react-native').FlatList;
  }
}
```
getFlatList 가 다음과같이 처리가 되어있어서 문제없다고 판단했고, 실제로 테스트해봤을때도 문제없이 동작하였습니다

2024-07-09 07:31 UTC, bang9 commented on sample/README.md
> +
ci 의 노드 버전 한번 변경해주실 수 있을까요?!
`.github > workflows > ci.yml` 파일에 node-version: 부분에 16.x -> 18.x 로 변경해주심 됩니다.

2024-07-09 07:32 UTC, bang9 requested changes
rebase 한번 해주실 수 있을까요?

`git rebase --onto main HEAD~10` (HEAD 에서부터 N 개만 리베이스)

2024-07-09 07:47 UTC, OnestarLee commented
> 커밋에 message thread 내용이 섞인것 같아서 ㅎㅎ rebase 한번 해주실 수 있을까요?
> 
> `git rebase --onto main HEAD~10` (HEAD 에서부터 N 개만 리베이스)

지금 상태가 reabse한 버전인데 혹시 섞인게 있을까요? 리베이스하면서 머지가 잘못된게 몇게 있어서 수정후에 다시 커밋하긴 했는데 현재 Files changed 50개 가 reabase된 상태라고 보시면 될거에요

2024-07-09 08:27 UTC, OnestarLee commented
테스트 관련 패키지들 버전업 하였습니다

2024-07-09 11:48 UTC, bang9 commented
> 지금 상태가 reabse한 버전인데 혹시 섞인게 있을까요? 리베이스하면서 머지가 잘못된게 몇개 있어서 수정후에 다시 커밋하긴 했는데 현재 Files changed 50개 가 reabase된 상태라고 보시면 될거에요

changes 를 대강 슥 봐서는 없는 것 같기는 한데, branch 가 나온곳이 메세지 스레드 작업하던 브랜치에서 나온 것 같습니다.
커밋들이 좀 섞여 있는것 같아가지고, 혹시 모르니 한번 하면 좋을 것 같아서요!

<img width="467" alt="image" src="https://github.com/sendbird/sendbird-uikit-react-native/assets/26326015/8248b63f-dbf5-4135-a017-f5096fed6e22">

2024-07-09 23:47 UTC, OnestarLee commented
이게 처음에 migrate-sample 브랜치 생성을 message-thread 기준으로 생성해서 복잡해 지긴했는데,  
message-thread -> main 으로 머지가된 후에 migrate-sample 을 main기준으로 rebase한상태입니다.
다행이도 migrate-sample에서 코드 관련해서 수정된부분이 별로 없어서 diff 확인하면서 잘못 머지된것들은 수정한 상태입니다.

2024-07-10 01:23 UTC, bang9 commented
>이게 처음에 migrate-sample 브랜치 생성을 message-thread 기준으로 생성해서 복잡해 지긴했는데,
message-thread -> main 으로 머지가된 후에 migrate-sample 을 main기준으로 rebase한상태입니다.
다행이도 migrate-sample에서 코드 관련해서 수정된부분이 별로 없어서 diff 확인하면서 잘못 머지된것들은 수정한 상태입니다.

네넵! 그러면 머지를 스쿼시로 하실거면 그대로 두어도 괜찮을 것 같고, 혹시나 머지 커밋으로 하실 예정이면 커밋 히스토리가 남으므로 리베이스를 한번 해주시면 좋을 것 같습니다~! (제가 권장드린 방식은 브랜치 분기 이후의 커밋들만 집어서 리베이스 하는거라, 일반적으로 서로 다른 작업인 경우 컨플릭이 발생하지 않습니다.)

알고 계실수도 있지만, Resolve 되었다고 하더라도 변경사항이 커밋 히스토리에 남아있어서 추가로 main 에 rebase 를 하실 일이 생기시면
작업과 관련 없는 변경사항들에 대해서 또 다시 conflict resolve 를 하게 되실수도 있어서, 전 요런것들을 피하기 위해 추가로 리베이스를 하니
요것도 나중에 한번 참고하시면 좋을 것 같습니다!

2024-07-10 01:40 UTC, OnestarLee commented
아하! 전 왜 계속 reabse를 요청하신지 이해가 안됬는데, 특정커밋만 리베이스를 하면 충돌도 방지하고 트리가 깔끔해 지는군요!! 전혀 모르고있었습니다 감사합니다 좋은거 배웠네요!! 
git은 센드버드 들어와서 처음 사용해보고, 그동안 팀작업할일이 많이 없어서 git 사용능력이 아직은 부족합니다~ 앞으로도 잘부탁드립니다 Airen!!
rebase 처리 다시하였습니다

2024-07-10 02:00 UTC, bang9 commented
> 아하! 전 왜 계속 reabse를 요청하신지 이해가 안됬는데, 특정커밋만 리베이스를 하면 충돌도 방지하고 트리가 깔끔해 지는군요!! 전혀 모르고있었습니다 감사합니다 좋은거 배웠네요!! git은 센드버드 들어와서 처음 사용해보고, 그동안 팀작업할일이 많이 없어서 git 사용능력이 아직은 부족합니다~ 앞으로도 잘부탁드립니다 Airen!! rebase 처리 다시하였습니다

아하 그런거였군요! 잘 몰랐습니다 ㅋㅋㅋ 넵 알겠습니다!

2024-07-11 06:27 UTC, bang9 approved these changes
CI 배포에서 깨지는 부분들을 일부 수정했습니다.
잘 돌아가네유!! 고생많으셨습니다 !!

2024-07-11 07:11 UTC, OnestarLee commented
엇 깨지는 부분이있었군요 감사합니다!

2024-07-11 07:13 UTC, merged